version: '3.8'

networks:
  app-network:
    driver: bridge

volumes:
  redis_volume_data:
    driver: local

services:
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    networks:
      - app-network
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass Rts28022007
    volumes:
      - redis_volume_data:/data
