spring:
  cache:
    type: redis
    cache-names: redis-caches
  data:
    redis:
      host: localhost
      port: 6379
      password:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: Rts28022007
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist

security:
  jwt:
    secret: U3VwZXJTZWNyZXRTZWNyZXRUb05vdmVvbmVDYW5EZWNyaXB0SXQ=
    access: 1
    refresh: 360
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml